// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/id.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserId struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03aadcbecca2a71, []int{0}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserIds struct {
	UserIds              []uint64 `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIds) Reset()         { *m = UserIds{} }
func (m *UserIds) String() string { return proto.CompactTextString(m) }
func (*UserIds) ProtoMessage()    {}
func (*UserIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03aadcbecca2a71, []int{1}
}

func (m *UserIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIds.Unmarshal(m, b)
}
func (m *UserIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIds.Marshal(b, m, deterministic)
}
func (m *UserIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIds.Merge(m, src)
}
func (m *UserIds) XXX_Size() int {
	return xxx_messageInfo_UserIds.Size(m)
}
func (m *UserIds) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIds.DiscardUnknown(m)
}

var xxx_messageInfo_UserIds proto.InternalMessageInfo

func (m *UserIds) GetUserIds() []uint64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type ID struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03aadcbecca2a71, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type IDs struct {
	Ids                  map[uint64]uint64 `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *IDs) Reset()         { *m = IDs{} }
func (m *IDs) String() string { return proto.CompactTextString(m) }
func (*IDs) ProtoMessage()    {}
func (*IDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03aadcbecca2a71, []int{3}
}

func (m *IDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDs.Unmarshal(m, b)
}
func (m *IDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDs.Marshal(b, m, deterministic)
}
func (m *IDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDs.Merge(m, src)
}
func (m *IDs) XXX_Size() int {
	return xxx_messageInfo_IDs.Size(m)
}
func (m *IDs) XXX_DiscardUnknown() {
	xxx_messageInfo_IDs.DiscardUnknown(m)
}

var xxx_messageInfo_IDs proto.InternalMessageInfo

func (m *IDs) GetIds() map[uint64]uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*UserId)(nil), "api.UserId")
	proto.RegisterType((*UserIds)(nil), "api.UserIds")
	proto.RegisterType((*ID)(nil), "api.ID")
	proto.RegisterType((*IDs)(nil), "api.IDs")
	proto.RegisterMapType((map[uint64]uint64)(nil), "api.IDs.IdsEntry")
}

func init() { proto.RegisterFile("api/id.proto", fileDescriptor_d03aadcbecca2a71) }

var fileDescriptor_d03aadcbecca2a71 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x50, 0xcf, 0x4b, 0xc3, 0x30,
	0x18, 0x5d, 0x93, 0xae, 0x1d, 0x5f, 0xa7, 0xe8, 0xc7, 0x90, 0xd2, 0x83, 0x94, 0xec, 0x32, 0x2f,
	0x19, 0x4c, 0x10, 0xf1, 0x38, 0x2a, 0x92, 0x8b, 0x87, 0x82, 0x20, 0xde, 0x32, 0x92, 0x43, 0x50,
	0xd6, 0x90, 0xb4, 0x62, 0xff, 0x7b, 0xe9, 0x8f, 0xc0, 0x6e, 0xdf, 0x7b, 0xdf, 0x7b, 0x79, 0x2f,
	0x1f, 0xac, 0xa5, 0x35, 0x7b, 0xa3, 0xb8, 0x75, 0x4d, 0xdb, 0x20, 0x95, 0xd6, 0xb0, 0x12, 0x92,
	0x0f, 0xaf, 0x9d, 0x50, 0x78, 0x07, 0x49, 0x37, 0x4e, 0x79, 0x54, 0x46, 0xbb, 0xb8, 0x9e, 0x11,
	0xdb, 0x42, 0x3a, 0x29, 0x3c, 0xe6, 0x90, 0x4e, 0xa4, 0xcf, 0xa3, 0x92, 0xee, 0xe2, 0x3a, 0x40,
	0xb6, 0x01, 0x22, 0x2a, 0xbc, 0x06, 0x62, 0x82, 0x9d, 0x18, 0xc5, 0x4e, 0x40, 0x45, 0xe5, 0x71,
	0x0b, 0xd4, 0xcc, 0x96, 0xec, 0x70, 0xcb, 0xa5, 0x35, 0x5c, 0x54, 0x9e, 0x0b, 0xe5, 0x5f, 0xcf,
	0xad, 0xeb, 0xeb, 0x61, 0x5b, 0x3c, 0xc1, 0x2a, 0x10, 0x78, 0x03, 0xf4, 0x5b, 0xf7, 0xf3, 0x43,
	0xc3, 0x88, 0x1b, 0x58, 0xfe, 0xca, 0x9f, 0x4e, 0xe7, 0x64, 0xe4, 0x26, 0xf0, 0x42, 0x9e, 0xa3,
	0xc3, 0x27, 0x64, 0x42, 0xbd, 0xe9, 0xb3, 0x76, 0xb2, 0x6d, 0x1c, 0xde, 0x43, 0xfc, 0xae, 0xff,
	0x5a, 0xcc, 0xc6, 0x98, 0xa9, 0x78, 0x91, 0xce, 0x99, 0x6c, 0x81, 0x0f, 0x70, 0x35, 0xec, 0x8f,
	0x7d, 0xf8, 0xd3, 0xfa, 0x42, 0xe8, 0x8b, 0x55, 0x68, 0xc7, 0x16, 0xc7, 0xf4, 0x6b, 0xc9, 0xf7,
	0xd2, 0x9a, 0x53, 0x32, 0xde, 0xeb, 0xf1, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x8b, 0xbf, 0xc1,
	0x3f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdGeneratorClient is the client API for IdGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdGeneratorClient interface {
	Next(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*ID, error)
	NextByUserIds(ctx context.Context, in *UserIds, opts ...grpc.CallOption) (*IDs, error)
}

type idGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewIdGeneratorClient(cc *grpc.ClientConn) IdGeneratorClient {
	return &idGeneratorClient{cc}
}

func (c *idGeneratorClient) Next(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/api.IdGenerator/Next", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idGeneratorClient) NextByUserIds(ctx context.Context, in *UserIds, opts ...grpc.CallOption) (*IDs, error) {
	out := new(IDs)
	err := c.cc.Invoke(ctx, "/api.IdGenerator/NextByUserIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdGeneratorServer is the server API for IdGenerator service.
type IdGeneratorServer interface {
	Next(context.Context, *UserId) (*ID, error)
	NextByUserIds(context.Context, *UserIds) (*IDs, error)
}

// UnimplementedIdGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedIdGeneratorServer struct {
}

func (*UnimplementedIdGeneratorServer) Next(ctx context.Context, req *UserId) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (*UnimplementedIdGeneratorServer) NextByUserIds(ctx context.Context, req *UserIds) (*IDs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextByUserIds not implemented")
}

func RegisterIdGeneratorServer(s *grpc.Server, srv IdGeneratorServer) {
	s.RegisterService(&_IdGenerator_serviceDesc, srv)
}

func _IdGenerator_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdGenerator/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorServer).Next(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdGenerator_NextByUserIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorServer).NextByUserIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdGenerator/NextByUserIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorServer).NextByUserIds(ctx, req.(*UserIds))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.IdGenerator",
	HandlerType: (*IdGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _IdGenerator_Next_Handler,
		},
		{
			MethodName: "NextByUserIds",
			Handler:    _IdGenerator_NextByUserIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/id.proto",
}
